name: example
description: Isolator example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  pedantic: ^1.9.2
  anitex: ^1.0.1
  dio: ^3.0.10
  cached_network_image: ^2.4.1
  flutter_fps: ^0.1.1
  statsfl: ^1.1.0+3
  string_similarity: ^1.1.0
  path_provider: ^1.6.24
  isolator:
    path: ./../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true